import fs from 'fs-extra';
import { REGISTRY_FILE, REPO_README } from './paths.js';

const EMPTY_REGISTRY = {
  version: 1,
  lastUpdated: null,
  members: {},
  skills: {},
};

export async function readRegistry() {
  if (!await fs.pathExists(REGISTRY_FILE)) {
    return { ...EMPTY_REGISTRY };
  }
  return fs.readJson(REGISTRY_FILE);
}

export async function writeRegistry(registry) {
  registry.lastUpdated = new Date().toISOString();
  await fs.writeJson(REGISTRY_FILE, registry, { spaces: 2 });
}

export async function addSkillToRegistry(registry, skillName, metadata, author, files, checksum) {
  registry.skills[skillName] = {
    name: metadata.name,
    description: metadata.description.slice(0, 300),
    author: metadata.author,
    skillVersion: metadata.version,
    date: metadata.date,
    pushedBy: author,
    pushedAt: new Date().toISOString(),
    files,
    hasAllowedTools: metadata.hasAllowedTools,
    checksum,
  };
  return registry;
}

export function registerMember(registry, author) {
  if (!registry.members) registry.members = {};

  const existing = registry.members[author];
  const skillsPushed = existing ? existing.skillsPushed : 0;

  registry.members[author] = {
    name: author,
    joinedAt: existing?.joinedAt || new Date().toISOString(),
    lastActiveAt: new Date().toISOString(),
    skillsPushed,
  };
  return registry;
}

export function incrementMemberPush(registry, author) {
  if (!registry.members) registry.members = {};
  if (registry.members[author]) {
    registry.members[author].skillsPushed = (registry.members[author].skillsPushed || 0) + 1;
    registry.members[author].lastActiveAt = new Date().toISOString();
  }
  return registry;
}

export async function removeSkillFromRegistry(registry, skillName) {
  delete registry.skills[skillName];
  return registry;
}

export async function generateReadme(registry, repoUrl) {
  const skillEntries = Object.values(registry.skills).sort((a, b) => a.name.localeCompare(b.name));
  const count = skillEntries.length;

  const rows = skillEntries.map(s => {
    const desc = s.description.split('\n')[0].trim().slice(0, 80);
    return `| ${s.name} | ${s.skillVersion} | ${s.author} | ${s.pushedBy} | ${s.date} | ${desc} |`;
  });

  const table = count > 0
    ? `| Skill | Version | Author | Pushed By | Date | Description |
|-------|---------|--------|-----------|------|-------------|
${rows.join('\n')}`
    : '_No skills shared yet. Run `skillsync push <skill-name>` to share your first skill._';

  const members = Object.values(registry.members || {}).sort((a, b) => b.skillsPushed - a.skillsPushed);
  const memberCount = members.length;

  const memberRows = members.map(m => {
    const joined = m.joinedAt ? m.joinedAt.split('T')[0] : '-';
    return `| ${m.name} | ${m.skillsPushed} | ${joined} |`;
  });

  const memberTable = memberCount > 0
    ? `| Member | Skills Pushed | Joined |
|--------|---------------|--------|
${memberRows.join('\n')}`
    : '_No members yet._';

  const readme = `# Shared Skills Registry

> Auto-generated by [SkillSync](https://github.com/OmarNassar1127/skillsync-team). Do not edit manually.

Last updated: ${registry.lastUpdated ? new Date(registry.lastUpdated).toUTCString() : 'Never'}

## Team (${memberCount})

${memberTable}

## Skills (${count})

${table}

## Usage

\`\`\`bash
npm install -g skillsync-team
skillsync init ${repoUrl || '<this-repo-url>'}
skillsync pull
\`\`\`

## How It Works

SkillSync syncs Claude Code skills between team members using this Git repository
as a shared registry. Skills are stored in \`~/.claude/skills/\` on each machine.

- **Push** a skill to share it with the team: \`skillsync push <skill-name>\`
- **Pull** to get the latest skills: \`skillsync pull\`
- **Team** overview: \`skillsync team\`
- **Auto-sync** with \`skillsync link\` for automatic pulls at session start

See the [SkillSync documentation](https://github.com/OmarNassar1127/skillsync-team) for full details.
`;

  await fs.writeFile(REPO_README, readme);
}
